main = "cat_finder_camera"

[[nodes]]
name = "det"
ty = "Detect"
model = "yolox-s"
conf = 0.25
nms = 0.45
tsize = 640
path = "models/cat_finder_models/yolox_s.mge"
interval = 5
visualize = 0
device = "cpu"
device_id = 0



[[nodes]]
name = "redis_proxy"
ty = "RedisSearch"
ip = "127.0.0.1"
port = "6379"
mode = "search"
prefix = "feature."


[[nodes]]
name = "reid_video"
ty = "ReID"
path = "models/cat_finder_models/resnet50.mge"
device = "cpu"
device_id = 1



[[graphs]]
name = "subgraph"
inputs = [{ name = "inp", cap = 16, ports = ["det:inp"] }]
outputs = [{ name = "out", cap = 16, ports = ["display:out"] }]
connections = [
  # Custom
  { cap = 16, ports = ["det:out", "track:inp"] },
  { cap = 16, ports = ["track:out", "shaper:inp"] },
  { cap = 16, ports = ["shaper:out", "reid_video:inp"] },
  { cap = 16, ports = ["reid_video:out", "redis_proxy:inp"] },
  { cap = 16, ports = ["redis_proxy:out", "name:inp"] },
  { cap = 16, ports = ["name:out", "display:inp"] },
]

    [[graphs.nodes]]
    name = "track"
    ty = "Track"

    [[graphs.nodes]]
    name = "shaper"
    ty = "Shaper"
    mode = "BEST"

    [[graphs.nodes]]
    name = "name"
    ty = "Name"

    [[graphs.nodes]]
    name = "display"
    ty = "Display"
    show_img = 1


[[graphs]]
name = "cat_finder_camera"
connections = [
  { cap = 16, ports = ["source:out", "destination:inp"] },
  { cap = 16, ports = ["source:inp", "destination:out"] }
]

    [[graphs.nodes]]
    name = "source"
    ty = "Capture"
    cap_id = "/home/rcxxx/Videos/two-cat-01.mp4"

    [[graphs.nodes]]
    name = "destination"
    ty = "subgraph"
