main = "cat_finder_camera"

[[nodes]]
name = "det"
ty = "Detect"
model = "yolox-s"
conf = 0.25
nms = 0.45
tsize = 640
path = "models/cat_finder_models/yolox_s.mge"
interval = 5
visualize = 0
device = "gpu"
device_id = 0

[[nodes]]
name = "redis_proxy"
ty = "RedisSearch"
ip = "127.0.0.1"
port = "6379"
prefix = "feature."
log = 0


[[nodes]]
name = "reid_video"
ty = "ReID"
path = "models/cat_finder_models/resnet50.mge"
device = "gpu"
device_id = 0
log = 0

[[nodes]]
name = "serial_port"
ty = "SerialPort"
port = "/dev/ttyTHS1"
baudrate = 115200
timeout = 0.01
serial_on = 0
log = 0


[[graphs]]
name = "subgraph"
inputs = [{ name = "inp", cap = 16, ports = ["serial_port:inp"] }]
outputs = [{ name = "out", cap = 16, ports = ["display:out"] }]
connections = [
  # Custom
  { cap = 16, ports = ["serial_port:out", "det:inp"] },
  { cap = 16, ports = ["det:out", "track:inp"] },
  { cap = 16, ports = ["track:out", "shaper:inp"] },
  { cap = 16, ports = ["shaper:out", "reid_video:inp"] },
  { cap = 16, ports = ["reid_video:out", "redis_proxy:inp"] },
  { cap = 16, ports = ["redis_proxy:out", "name:inp"] },
  { cap = 16, ports = ["name:out", "feeder:inp"] },
  { cap = 16, ports = ["feeder:food", "nano-gpio:inp"] },
  { cap = 16, ports = ["feeder:out", "display:inp"] },
]

    [[graphs.nodes]]
    name = "track"
    ty = "Track"
    log = 0

    [[graphs.nodes]]
    name = "shaper"
    ty = "Shaper"
    mode = "BEST"
    log = 0

    [[graphs.nodes]]
    name = "name"
    ty = "Name"
    log = 0

    [[graphs.nodes]]
    name = "display"
    ty = "Display"
    show_img = 1
    log = 0

    [[graphs.nodes]]
    name = "feeder"
    ty = "Feeder"
    ip = "127.0.0.1"
    port = "6379"
    preset_time = 0
    cat_wait_time = 3
    amount_dt = 20
    times_dt = 5
    amount_ts = 30
    times_ts = 5
    log = 1

    [[graphs.nodes]]
    name = "nano-gpio"
    ty = "NanoGPIO"
    nano = 0
    gpio = 37
    log = 1

[[graphs]]
name = "cat_finder_camera"
connections = [
  { cap = 16, ports = ["source:out", "destination:inp"] },
  { cap = 16, ports = ["source:inp", "destination:out"] }
]

    [[graphs.nodes]]
    name = "source"
    ty = "Capture"
    cap_id = 0

    [[graphs.nodes]]
    name = "destination"
    ty = "subgraph"
